from flask import Flask
from flask_sqlalchemy import SQLAlchemy
from models import Extraction, db
from flickrScraper import search
from ImageScraper import scrap 
import threading,requests, os, urllib


'''googleScraper_url is a list that will contain the links generated by the GoogleScraper'''
i = 0
googleScraper_url = [None] * 30

 
'''photo holds a list of the parameters generated by the flickrAPI'''
photo = search('India', 1).get('photo')

'''url_list contains the return value generated by the ImageScraper module, which in turn is a list of unparsed URL links'''
url_list = scrap('auli')
for item in url_list:
	googleScraper_url[i] = urllib.parse.unquote(item)
	i +=1


'''Adding the paramters and links to the table in the database'''
for item in photo:
	elements = Extraction(flickr_height = item['height_o'],
					flickr_width = item['width_o'],
					flickr_title = item['title'],
					flickr_url = item['url_o'],
					googleScraper_url = None)

for item in googleScraper_url:
	elements = Extraction(googleScraper_url = item)


elements.save()
	
